// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	site: 'https://basehub.org',
	integrations: [
		starlight({
			title: 'BaseHub',
			logo: {
				src: './src/assets/basehub-logo.png',
			},
			customCss: [
				'./src/styles/theme.css',
				'./src/styles/code.css',
				'./src/styles/homepage.css',
			],
			expressiveCode: {
				themes: ['github-light'],
				useStarlightDarkModeSwitch: false,
				styleOverrides: {
					borderRadius: '8px',
					borderColor: 'var(--code-border)',
					codeFontFamily: 'var(--sl-font-mono)',
					codeFontSize: '0.8125rem',
					codeLineHeight: '1.6',
					uiFontFamily: 'var(--sl-font-mono)',
					uiFontSize: '0.75rem',
					frames: {
						frameBoxShadowCssValue: 'none',
						editorActiveTabIndicatorBottomColor: 'var(--sl-color-accent)',
						editorActiveTabBorderColor: 'transparent',
						editorTabBarBorderBottomColor: 'var(--code-border)',
						terminalTitlebarBorderBottomColor: 'var(--code-border)',
						terminalBackground: 'var(--code-bg)',
						editorBackground: 'var(--code-bg)',
					},
				},
			},
			head: [
				{
					tag: 'script',
					content:
						"document.documentElement.dataset.theme='light';try{localStorage.setItem('starlight-theme','light');}catch(_){}",
				},
				{ tag: 'meta', attrs: { property: 'og:site_name', content: 'BaseHub' } },
				{ tag: 'meta', attrs: { property: 'og:type', content: 'website' } },
				{ tag: 'meta', attrs: { property: 'og:image', content: 'https://basehub.org/og-default.png' } },
				{ tag: 'meta', attrs: { property: 'og:image:width', content: '1200' } },
				{ tag: 'meta', attrs: { property: 'og:image:height', content: '630' } },
				{ tag: 'meta', attrs: { property: 'og:image:alt', content: 'BaseHub — reference for agents on Base' } },
				{ tag: 'meta', attrs: { property: 'og:locale', content: 'en_US' } },
				{ tag: 'meta', attrs: { name: 'twitter:card', content: 'summary_large_image' } },
				{ tag: 'meta', attrs: { name: 'twitter:image', content: 'https://basehub.org/og-default.png' } },
				{ tag: 'meta', attrs: { name: 'twitter:image:alt', content: 'BaseHub — reference for agents on Base' } },
				{ tag: 'meta', attrs: { name: 'theme-color', content: '#0000ff' } },
				{ tag: 'link', attrs: { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32.png' } },
				{ tag: 'link', attrs: { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-16.png' } },
				{ tag: 'link', attrs: { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' } },
				{
					tag: 'script',
					attrs: { type: 'application/ld+json' },
					content: JSON.stringify({
						'@context': 'https://schema.org',
						'@type': 'WebSite',
						name: 'BaseHub',
						url: 'https://basehub.org',
						description: 'Every page is reachable as raw Markdown by appending .md to the URL.',
						publisher: { '@type': 'Organization', name: 'BaseHub', url: 'https://basehub.org' },
					}),
				},
				{
					tag: 'script',
					attrs: {
						async: true,
						defer: true,
						src: 'https://scripts.simpleanalyticscdn.com/latest.js',
					},
				},
				{
					tag: 'noscript',
					content: '<img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" />',
				},
			],
			editLink: {
				baseUrl: 'https://github.com/wbnns/basehub/edit/main/',
			},
			components: {
				Head: './src/components/Head.astro',
				Footer: './src/components/Footer.astro',
				SiteTitle: './src/components/SiteTitle.astro',
			},
			sidebar: [
				{
					label: 'Introduction',
					items: [
						{ label: 'Why Base', slug: 'introduction/why-base' },
						{ label: 'Connecting to Base', slug: 'introduction/connecting-to-base' },
						{ label: 'Deploy on Base', slug: 'introduction/deploy-on-base' },
						{ label: 'Base ↔ Solana Bridge', slug: 'introduction/base-solana-bridge' },
					],
				},
				{
					label: 'Network',
					items: [
						{ label: 'Base Contracts', slug: 'network/base-contracts' },
						{ label: 'Ecosystem Contracts', slug: 'network/ecosystem-contracts' },
						{ label: 'Bridges', slug: 'network/bridges' },
							{ label: 'Bridging and Withdrawals', slug: 'network/bridging-and-withdrawals' },
						{ label: 'Network Fees', slug: 'network/network-fees' },
						{ label: 'Faucets', slug: 'network/network-faucets' },
						{ label: 'Transaction Finality', slug: 'network/transaction-finality' },
						{ label: 'Block Building', slug: 'network/block-building' },
							{ label: 'Throughput and Limits', slug: 'network/throughput-and-limits' },
						{ label: 'Base vs. Ethereum', slug: 'network/diffs-ethereum-base' },
						{ label: 'Configuration Changelog', slug: 'network/configuration-changelog' },
						{ label: 'Troubleshooting Transactions', slug: 'network/troubleshooting-transactions' },
					],
				},
				{
					label: 'Flashblocks',
					items: [
						{ label: 'Overview', slug: 'flashblocks/overview' },
						{ label: 'Architecture', slug: 'flashblocks/architecture' },
						{ label: 'App Integration', slug: 'flashblocks/app-integration' },
						{ label: 'FAQ', slug: 'flashblocks/faq' },
					],
				},
				{
					label: 'API Reference',
					items: [
						{ label: 'RPC Overview', slug: 'api-reference/rpc-overview' },
						{ label: 'Rollup Node RPC', slug: 'api-reference/rollup-node-rpc' },
						{
							label: 'Ethereum JSON-RPC',
							collapsed: true,
							items: [
								{ label: 'eth_blockNumber', slug: 'api-reference/eth/eth_blocknumber' },
								{ label: 'eth_call', slug: 'api-reference/eth/eth_call' },
								{ label: 'eth_chainId', slug: 'api-reference/eth/eth_chainid' },
								{ label: 'eth_estimateGas', slug: 'api-reference/eth/eth_estimategas' },
								{ label: 'eth_feeHistory', slug: 'api-reference/eth/eth_feehistory' },
								{ label: 'eth_gasPrice', slug: 'api-reference/eth/eth_gasprice' },
								{ label: 'eth_getBalance', slug: 'api-reference/eth/eth_getbalance' },
								{ label: 'eth_getBlockByHash', slug: 'api-reference/eth/eth_getblockbyhash' },
								{ label: 'eth_getBlockByNumber', slug: 'api-reference/eth/eth_getblockbynumber' },
								{ label: 'eth_getBlockReceipts', slug: 'api-reference/eth/eth_getblockreceipts' },
								{ label: 'eth_getBlockTransactionCountByHash', slug: 'api-reference/eth/eth_getblocktransactioncountbyhash' },
								{ label: 'eth_getBlockTransactionCountByNumber', slug: 'api-reference/eth/eth_getblocktransactioncountbynumber' },
								{ label: 'eth_getCode', slug: 'api-reference/eth/eth_getcode' },
								{ label: 'eth_getLogs', slug: 'api-reference/eth/eth_getlogs' },
								{ label: 'eth_getStorageAt', slug: 'api-reference/eth/eth_getstorageat' },
								{ label: 'eth_getTransactionByBlockHashAndIndex', slug: 'api-reference/eth/eth_gettransactionbyblockhashandindex' },
								{ label: 'eth_getTransactionByBlockNumberAndIndex', slug: 'api-reference/eth/eth_gettransactionbyblocknumberandindex' },
								{ label: 'eth_getTransactionByHash', slug: 'api-reference/eth/eth_gettransactionbyhash' },
								{ label: 'eth_getTransactionCount', slug: 'api-reference/eth/eth_gettransactioncount' },
								{ label: 'eth_getTransactionReceipt', slug: 'api-reference/eth/eth_gettransactionreceipt' },
								{ label: 'eth_maxPriorityFeePerGas', slug: 'api-reference/eth/eth_maxpriorityfeepergas' },
								{ label: 'eth_sendRawTransaction', slug: 'api-reference/eth/eth_sendrawtransaction' },
								{ label: 'eth_subscribe', slug: 'api-reference/eth/eth_subscribe' },
								{ label: 'eth_syncing', slug: 'api-reference/eth/eth_syncing' },
								{ label: 'eth_unsubscribe', slug: 'api-reference/eth/eth_unsubscribe' },
								{ label: 'net_version', slug: 'api-reference/eth/net_version' },
								{ label: 'web3_clientVersion', slug: 'api-reference/eth/web3_clientversion' },
							],
						},
						{
							label: 'Debug API',
							collapsed: true,
							items: [
								{ label: 'debug_traceBlockByHash', slug: 'api-reference/debug/debug_traceblockbyhash' },
								{ label: 'debug_traceBlockByNumber', slug: 'api-reference/debug/debug_traceblockbynumber' },
								{ label: 'debug_traceTransaction', slug: 'api-reference/debug/debug_tracetransaction' },
							],
						},
						{
							label: 'Flashblocks API',
							collapsed: true,
							items: [
								{ label: 'Overview', slug: 'api-reference/flashblocks/overview' },
								{ label: 'newFlashblocks', slug: 'api-reference/flashblocks/newflashblocks' },
								{ label: 'newFlashblockTransactions', slug: 'api-reference/flashblocks/newflashblocktransactions' },
								{ label: 'pendingLogs', slug: 'api-reference/flashblocks/pendinglogs' },
								{ label: 'eth_simulateV1', slug: 'api-reference/flashblocks/eth_simulatev1' },
								{ label: 'base_transactionStatus', slug: 'api-reference/flashblocks/base_transactionstatus' },
							],
						},
					],
				},
				{
					label: 'Run a Node',
					items: [
						{ label: 'Prerequisites', slug: 'getting-started/prerequisites' },
						{ label: 'Building', slug: 'getting-started/building' },
						{ label: 'Docker', slug: 'getting-started/docker' },
						{ label: 'Running', slug: 'getting-started/running' },
						{ label: 'Development', slug: 'getting-started/development' },
						{ label: 'Devnet', slug: 'getting-started/devnet' },
					],
				},
				{
					label: 'Crate Reference',
					items: [
						{ label: 'Overview', slug: 'crates/overview' },
						{
							label: 'alloy',
							collapsed: true,
							items: [
								{ label: 'Overview', slug: 'crates/alloy/overview' },
								{ label: 'consensus', slug: 'crates/alloy/consensus' },
								{ label: 'evm', slug: 'crates/alloy/evm' },
								{ label: 'hardforks', slug: 'crates/alloy/hardforks' },
								{ label: 'network', slug: 'crates/alloy/network' },
								{ label: 'provider', slug: 'crates/alloy/provider' },
								{ label: 'rpc-jsonrpsee', slug: 'crates/alloy/rpc-jsonrpsee' },
								{ label: 'rpc-types-engine', slug: 'crates/alloy/rpc-types-engine' },
								{ label: 'rpc-types', slug: 'crates/alloy/rpc-types' },
							],
						},
						{
							label: 'builder',
							collapsed: true,
							items: [
								{ label: 'Overview', slug: 'crates/builder/overview' },
								{ label: 'core', slug: 'crates/builder/core' },
								{ label: 'metering', slug: 'crates/builder/metering' },
								{ label: 'publish', slug: 'crates/builder/publish' },
							],
						},
						{
							label: 'client',
							collapsed: true,
							items: [
								{ label: 'Overview', slug: 'crates/client/overview' },
								{ label: 'cli', slug: 'crates/client/cli' },
								{ label: 'engine', slug: 'crates/client/engine' },
								{ label: 'flashblocks-node', slug: 'crates/client/flashblocks-node' },
								{ label: 'flashblocks', slug: 'crates/client/flashblocks' },
								{ label: 'metering', slug: 'crates/client/metering' },
								{ label: 'proofs', slug: 'crates/client/proofs' },
								{ label: 'txpool-tracing', slug: 'crates/client/txpool-tracing' },
							],
						},
						{
							label: 'consensus',
							collapsed: true,
							items: [
								{ label: 'Overview', slug: 'crates/consensus/overview' },
								{ label: 'cli', slug: 'crates/consensus/cli' },
								{ label: 'derive', slug: 'crates/consensus/derive' },
								{ label: 'disc', slug: 'crates/consensus/disc' },
								{ label: 'engine', slug: 'crates/consensus/engine' },
								{ label: 'genesis', slug: 'crates/consensus/genesis' },
								{ label: 'gossip', slug: 'crates/consensus/gossip' },
								{ label: 'hardforks', slug: 'crates/consensus/hardforks' },
								{ label: 'macros', slug: 'crates/consensus/macros' },
								{ label: 'peers', slug: 'crates/consensus/peers' },
								{ label: 'protocol', slug: 'crates/consensus/protocol' },
								{ label: 'providers-alloy', slug: 'crates/consensus/providers-alloy' },
								{ label: 'registry', slug: 'crates/consensus/registry' },
								{ label: 'rpc', slug: 'crates/consensus/rpc' },
								{ label: 'service', slug: 'crates/consensus/service' },
								{ label: 'sources', slug: 'crates/consensus/sources' },
							],
						},
						{
							label: 'execution',
							collapsed: true,
							items: [
								{ label: 'Overview', slug: 'crates/execution/overview' },
								{ label: 'chainspec', slug: 'crates/execution/chainspec' },
								{ label: 'cli', slug: 'crates/execution/cli' },
								{ label: 'consensus', slug: 'crates/execution/consensus' },
								{ label: 'evm', slug: 'crates/execution/evm' },
								{ label: 'exex', slug: 'crates/execution/exex' },
								{ label: 'hardforks', slug: 'crates/execution/hardforks' },
								{ label: 'node', slug: 'crates/execution/node' },
								{ label: 'payload', slug: 'crates/execution/payload' },
								{ label: 'primitives', slug: 'crates/execution/primitives' },
								{ label: 'reth', slug: 'crates/execution/reth' },
								{ label: 'rpc', slug: 'crates/execution/rpc' },
								{ label: 'storage', slug: 'crates/execution/storage' },
								{ label: 'trie', slug: 'crates/execution/trie' },
								{ label: 'txpool', slug: 'crates/execution/txpool' },
							],
						},
						{
							label: 'infra',
							collapsed: true,
							items: [
								{ label: 'Overview', slug: 'crates/infra/overview' },
								{ label: 'audit', slug: 'crates/infra/audit' },
								{ label: 'basectl', slug: 'crates/infra/basectl' },
								{ label: 'based', slug: 'crates/infra/based' },
								{ label: 'ingress-rpc', slug: 'crates/infra/ingress-rpc' },
								{ label: 'mempool-rebroadcaster', slug: 'crates/infra/mempool-rebroadcaster' },
								{ label: 'system-tests', slug: 'crates/infra/system-tests' },
								{ label: 'websocket-proxy', slug: 'crates/infra/websocket-proxy' },
							],
						},
						{
							label: 'proof',
							collapsed: true,
							items: [
								{ label: 'Overview', slug: 'crates/proof/overview' },
								{ label: 'driver', slug: 'crates/proof/driver' },
								{ label: 'executor', slug: 'crates/proof/executor' },
								{ label: 'mpt', slug: 'crates/proof/mpt' },
								{ label: 'preimage', slug: 'crates/proof/preimage' },
								{ label: 'proof', slug: 'crates/proof/proof' },
								{ label: 'std-fpvm', slug: 'crates/proof/std-fpvm' },
								{ label: 'std-fpvm-proc', slug: 'crates/proof/std-fpvm-proc' },
							],
						},
						{
							label: 'shared',
							collapsed: true,
							items: [
								{ label: 'Overview', slug: 'crates/shared/overview' },
								{ label: 'access-lists', slug: 'crates/shared/access-lists' },
								{ label: 'bundles', slug: 'crates/shared/bundles' },
								{ label: 'cli-utils', slug: 'crates/shared/cli-utils' },
								{ label: 'engine-ext', slug: 'crates/shared/engine-ext' },
								{ label: 'jwt', slug: 'crates/shared/jwt' },
								{ label: 'node', slug: 'crates/shared/node' },
								{ label: 'primitives', slug: 'crates/shared/primitives' },
								{ label: 'reth-rpc-types', slug: 'crates/shared/reth-rpc-types' },
								{ label: 'txpool-rpc', slug: 'crates/shared/txpool-rpc' },
							],
						},
					],
				},
				{
					label: 'Integration Guides',
					items: [
						{ label: 'Connecting to Base', slug: 'integration-guides/connecting' },
						{ label: 'Flashblocks RPC', slug: 'integration-guides/flashblocks-rpc' },
						{ label: 'Metering RPC', slug: 'integration-guides/metering-rpc' },
						{ label: 'Transaction Pool', slug: 'integration-guides/txpool' },
					],
				},
				{
					label: 'Node Operations',
					items: [
						{ label: 'Deployment', slug: 'node-operations/deployment' },
						{ label: 'Docker', slug: 'node-operations/docker' },
						{ label: 'Configuration', slug: 'node-operations/configuration' },
						{ label: 'Monitoring', slug: 'node-operations/monitoring' },
						{ label: 'Snapshots', slug: 'node-operations/snapshots' },
						{ label: 'Performance Tuning', slug: 'node-operations/performance-tuning' },
						{ label: 'Node Providers', slug: 'node-operations/node-providers' },
						{ label: 'Troubleshooting', slug: 'node-operations/troubleshooting' },
						{ label: 'Upgrades', slug: 'node-operations/upgrades' },
						{ label: 'Azul Node Upgrade', slug: 'node-operations/azul-node-upgrade' },
						{ label: 'Base v1 Upgrade', slug: 'node-operations/base-v1-upgrade' },
						{ label: 'Releases', slug: 'node-operations/releases' },
						{ label: 'Release Process', slug: 'node-operations/release-process' },
						{ label: 'basectl', slug: 'node-operations/basectl' },
					],
				},
				{
					label: 'Architecture',
					items: [
						{ label: 'Overview', slug: 'architecture/overview' },
						{ label: 'Protocol Overview', slug: 'architecture/protocol-overview' },
						{ label: 'Crate Graph', slug: 'architecture/crate-graph' },
						{ label: 'Execution Pipeline', slug: 'architecture/execution-pipeline' },
						{ label: 'Flashblocks Pipeline', slug: 'architecture/flashblocks-pipeline' },
						{ label: 'June 2026 Outage Postmortem', slug: 'architecture/june-2026-block-production-outage' },
						{ label: 'Native Account Abstraction', slug: 'architecture/native-account-abstraction' },
					],
				},
				{
					label: 'Binaries',
					items: [
						{ label: 'base-reth-node', slug: 'binaries/base-reth-node' },
						{ label: 'basectl', slug: 'binaries/basectl' },
						{ label: 'based', slug: 'binaries/based' },
						{ label: 'builder', slug: 'binaries/builder' },
						{ label: 'consensus', slug: 'binaries/consensus' },
						{ label: 'ingress-rpc', slug: 'binaries/ingress-rpc' },
						{ label: 'mempool-rebroadcaster', slug: 'binaries/mempool-rebroadcaster' },
						{ label: 'websocket-proxy', slug: 'binaries/websocket-proxy' },
						{ label: 'audit-archiver', slug: 'binaries/audit-archiver' },
					],
				},
				{
					label: 'Specifications',
					items: [
						{ label: 'Flashblocks', slug: 'specifications/flashblocks' },
						{ label: 'Access Lists (FAL)', slug: 'specifications/access-lists' },
						{ label: 'P2P', slug: 'specifications/p2p' },
						{ label: 'Configuration', slug: 'specifications/configuration' },
						{ label: 'Isthmus Execution Engine', slug: 'specifications/isthmus-exec-engine' },
						{ label: 'Jovian Execution Engine', slug: 'specifications/jovian-exec-engine' },
						{ label: 'Azul Execution Engine', slug: 'specifications/azul-exec-engine' },
						{ label: 'Beryl Upgrade Overview', slug: 'specifications/beryl-overview' },
						{ label: 'B20 Token Standard', slug: 'specifications/b20' },
						{ label: 'Reth V2', slug: 'specifications/reth-v2' },
						{ label: 'Transaction Event Journal', slug: 'specifications/transaction-events' },
						{ label: 'Glossary', slug: 'specifications/glossary' },
					],
				},
				{
					label: 'Security',
					items: [
						{ label: 'Bug Bounty', slug: 'security/bug-bounty' },
						{ label: 'Report a Vulnerability', slug: 'security/report-vulnerability' },
						{ label: 'Security Council', slug: 'security/security-council' },
						{ label: 'Avoid Malicious Flags', slug: 'security/avoid-malicious-flags' },
					],
				},
				{
					label: 'Contributing',
					slug: 'contributing',
				},
			],
		}),
	],
});
